# This is a Portable configuration, using TOML 1.1.0
# For syntax, check https://toml.io/en/v1.1.0
[metadata]
appID = "com.discordapp.Discord"

# This is a friendly name of an application. It should only contain ASCII characters and not spaces.
friendlyName = "Discord"

# This is the state directory of your application, relative to "XDG_DATA_HOME".
stateDirectory = "Discord_Data"

# The exec section defines how the underlying process is started.
[exec]
# target defines the program to start.
target = "discord"

# arguments holds an array of arguments passed to the application, this is also used when starting secondary instances.
arguments = []

# The processes section defines how Portable tracks tasks.
[processes]
# Watch for spawned commands. When all of them exits, automatically terminate the sandbox. Defaults to true.
track = true

# The system section controls general permission.
[system]
# Whether or not an application can call Inhibit Portal to prevent automatic suspend. Defaults to false.
inhibitSuspend = true

# Whether or not an application can call GlobalShortcuts Portal to request shortcuts registration. Defaults to false.
globalShortcuts = true

# Whether or not to expose all GPUs and prefer discrete graphics card. By default, Portable blocks any GPU except the integrated one to improve user experience and power consumption on hybrid systems.
gameMode = false

# The network section defines behaviour of Portable's network firewall. Requires netsock for filtering.
[network]
# Whether or not an application can use network interfaces. Defaults to true.
enable = true

# Whether or not to enable filtering on network packets. Defaults to false.
filter = true

# Destinations to deny. Only effective if netsock is running and listening on /run/netsock/control.sock. IP literals are resolved directly, while strings are mapped to IP addresses by the system resolver. A special string of "private" means private IPs. Note that :53 is allowed regardless to avoid breaking DNS. Defaults to none, meaning sandbox can connect to whatever address.
filterDest = ["private"]

# The privacy section defines several device exposure preference. By default, Portable does not allow apps to see physical devices. This includes discrete GPUs when gameMode is off, input devices, cameras, and all other PCI devices.
[privacy]
# When false, prevents application from connecting to X server on Wayland. Defaults to true.
x11 = true

# When false, prevents application from connecting to legacy notifications endpoint. Defaults to true.
classicNotifications = true

# When true, exposes camera devices in the sandbox. Defaults to false.
cameras = false

# When true, allows application to connect to PipeWire server. Note that a proxy is set up to prevent privileged actions. Defaults to false.
pipeWire = false

# When true, allows application to receive Input events, particularly useful for Games. Defaults to false.
input = false