#!/usr/bin/env bash


# 没有参数 → 默认运行
if [ $# -eq 0 ]; then
    PORTABLE_CONF=cn.wps.wps_365 portable

# 有参数 → 解析路径并绑定
else
    FILE="$1"
    DIR="$(dirname "$FILE")"

    PORTABLE_CONF=cn.wps.wps_365 exec portable \
	    --expose "$FILE" "/tmp/$(basename "$FILE")" \
	    -- "$FILE"
fi
