# This is a Portable configuration, using TOML 1.1.0
# For syntax, check https://toml.io/en/v1.1.0

# The metadata section contains information of your sandbox.
[metadata]
# This is your Application ID, avoid conflict. Should be a reversed DNS name.
# If the author's DNS domain name contains hyphen/minus characters ('-'), which are not allowed in D-Bus interface names, they should be replaced by underscores. If the DNS domain name contains a digit immediately following a period ('.'), which is also not allowed in interface names), the interface name should add an underscore before that digit. For example, if the owner of 7-zip.org defined an interface for out-of-process plugins, it might be named org._7_zip.Plugin.
appID = "com.steampowered"

# This is a friendly name of an application. It should only contain ASCII characters and not spaces.
friendlyName = "Steam"

# This is the state directory of your application, relative to "XDG_DATA_HOME".
stateDirectory = "Steam_Data"

# The exec section defines how the underlying process is started.
[exec]
# target defines the program to start.
target = "env"

# arguments holds an array of arguments passed to the application, this is also used when starting secondary instances.
arguments = ["SDL_VIDEO_DRIVER=x11", "steam"]

overlay = true

# The processes section defines how Portable tracks tasks.
[processes]
# Watch for spawned commands. When all of them exits, automatically terminate the sandbox. Defaults to true.
track = true

# The system section controls general permission.
[system]
# Whether or not an application can call Inhibit Portal to prevent automatic suspend. Defaults to false.
inhibitSuspend = true

# A TOML slice that accepts string values.
# Current possible values are: (dgpu, input, camera, kvm).
#------------------------------------------------------------------------------#
## dgpu (or gamemode): Expose all GPUs and prefer discrete graphics card.
## By default,
## 	Portable blocks any GPU except the integrated one
## 	to improve user experience and power consumption on hybrid systems.
## This is not available when Power Profile is set to Power Saver.
#------------------------------------------------------------------------------#
## kvm: Enables access to the Kernel-based Virtual Machine (/dev/kvm), if any.
#------------------------------------------------------------------------------#
## camera: Enables access to physical camera devices. Modern applications should
## 	talk with Portals instead, while legacy ones may still need device node
## 	access.
#------------------------------------------------------------------------------#
## input: Allows applications to receive Input events.
## In addition, the kernel uinput device is made available for Steam Input.
## It is intended for Games to make use of Controllers,
## 	but said permission might introduce input snooping if the device node
## 	for keyboards and mouses are messed up.
#------------------------------------------------------------------------------#
deviceAllow = ["input", "dgpu"]

# Inhibit suspend and idle on behalf of applications. Requires system.inhibitSuspend being true
inhibitOnBehalf = true

# The network section defines behaviour of Portable's network firewall. Requires netsock for filtering.
[network]
# Whether or not an application can use network interfaces. Defaults to true.
enable = true

# The privacy section defines several device exposure preference. By default, Portable does not allow apps to see physical devices. This includes discrete GPUs when gameMode is off, input devices, cameras, and all other PCI devices.
[privacy]
# When false, prevents application from connecting to X server on Wayland. Defaults to true.
x11 = true

# When false, prevents application from connecting to legacy notifications endpoint. Defaults to true.
classicNotifications = true

# Do not use. May break apps.
[advanced]
zink = false
qt5Compat = true
mprisName = []
trayWake = false
kDEStatus = false
flatpakInfo = false