# This is a basic workflow to help you get started with Actions

name: Builder for all packages

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install git
        run: pacman -Syu --noconfirm git
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Update repo
        run: |
          git config --global --add safe.directory .
          git switch master
          git pull --all
          git switch -
      - name: Determine updated package
        run: |
          git status
          changed_dirs=$(git diff origin/master...HEAD --name-only | grep '/' | cut -d '/' -f 1,2 | sort -u)
          updated_pkgs=()
          for dir in $changed_dirs; do
            # Check if both required files exist in that directory
            if [[ -f "$dir/stashpak.toml" ]] && [[ -f "$dir/PKGBUILD" ]]; then
            # Extract just the pkgname (the second part of the path)
            pkgname=$(echo "$dir" | cut -d '/' -f 2)
            updated_pkgs+=("$pkgname")
            fi
          done
          echo "${updated_pkgs[@]}" | xargs > $GITHUB_WORKSPACE/.updated

      - name: Print updated package
        run: |
          cat $GITHUB_WORKSPACE/.updated
      - name: Add archlinuxcn repository and install StashPak
        run: |
          echo "[archlinuxcn]" >>/etc/pacman.conf
          echo 'Server = https://repo.archlinuxcn.org/$arch' >>/etc/pacman.conf
          pacman-key --init
          pacman -Sy --noconfirm archlinuxcn-keyring
          pacman -Syu --noconfirm stashpak sudo
      - name: Build delta
        run: |
          sysctl -w kernel.unprivileged_userns_clone=1
          export stashPakElevateProgram="sudo"
          export XDG_RUNTIME_DIR=/tmp
          currDir="$(pwd)"
          for pkg in $(cat $GITHUB_WORKSPACE/.updated); do
            echo "Building package: $pkg"
            if [[ -d ./"x86_64/${pkg}" ]]; then
              echo "Building x86_64"
              cd ./"x86_64/${pkg}"
              stashpak install-local
              cd "${currDir}"
            fi
          done
